### ISSUE TITLE
Error when closing Dialog

### ISSUE THREAD

**Issue by mishoboss** [OnsenUI/react-onsenui#45] opened 2016-06-19 21:31 UTC
`util.js:247 Uncaught SyntaxError: Unexpected token (  
index.js:275(anonymous function) @ index.js:400(anonymous function) @ animator.js:140_dequeueTransition @ animit.js:474done @ animit.js:467(anonymous function) @ animit.js:411_dequeueTransition @ animit.js:474done @ animit.js:467(anonymous function) @ animit.js:529fn @ animit.js:66`

**Comment by philolo1** [comment] 2016-06-20 00:09
Thanks for reporting! This is actually a bug in chrome due to some naming
issues of the event, but it does not cause any error.

**Comment by philolo1** [comment] 2016-06-20 03:11
@mishoboss closing this issue since its a chrome bug,

**Comment by philolo1** [comment] 2016-06-20 03:11
if this causes any real error feel free to open the issue again.

**Closed by philolo1** 2016-06-20 03:11 UTC

**Comment by mishoboss** [comment] 2016-06-20 05:46
Seems not causing any real issues, just a nasty console error log.

**Comment by argelius** [comment] 2016-06-20 06:33
@philolo1 @mishoboss Maybe we should take a look at this again. The error message is very ugly even if it doesn't do anything... :(

**Comment by argelius** [comment] 2016-06-20 06:43
Apparently it is caused by emitting an event with the name `cancel`. Chrome doesn't like that name :)

**Comment by argelius** [comment] 2016-06-21 10:04
@mishoboss We have released a new version that fixes this error.
