### ISSUE TITLE
Navigator does not update pages when a re-render is triggered

### ISSUE THREAD

**Issue by mancas** [OnsenUI/react-onsenui#94] opened 2016-08-01 12:01 UTC
If you try to `setState` from the navigator parent element, the pages don't receive the update until you click somewhere on the screen. What I'm trying to do is type in an input and filter the results.

I've tried to update the sate of each page when navigator receives `componentWillUpdate`:

`
{
      key: 'componentWillUpdate',
      value: function componentWillUpdate() {
        var _this7 = this;
        this.pages = this.routes.map(function (route) {
          return _this7.props.renderPage(route, _this7);
        });
      }
    }
`

The code above works but it breaks the navigation stack. Any thoughts?

**Comment by matoilic** [comment] 2016-08-01 17:26
Just ran in the same issue. This is a major bug since it breaks React standard behaviour. I've created an example here https://codepen.io/matoilic/pen/pbOvaG?editors=0010. When calling `forceUpdate` lifecycle methods like `shouldComponentUpdate` on the children should be invoked. This is not the case when using the Navigator component.

**Comment by argelius** [comment] 2016-08-03 07:43
@mancas @matoilic Thanks! We will fix this issue.

**Comment by argelius** [comment] 2016-08-05 04:55
@mancas @matoilic I have made some changes to the Navigator so it will re-render its children.

The changes are pretty large so we need to do some testing and review as to not break anything.

You can follow the progress here:
https://github.com/OnsenUI/react-onsenui/pull/101

**Comment by philolo1** [comment] 2016-08-12 01:08
@argelius you try to rerender all the pages all the time, do we really want to do it.?The proper way is to rerender the page and not the navigator. You would kind or reset the entire navigator, that should be the behaviour you are expecting?
@matoilic @mancas So what do you expect to rerender everything with the routes? The routes are called `initialRoute` and means its a starting point. With the new Navigator we are working on that has redux like behaviour it would make more sense and i get what you want to do here, but with the current navigator if you change the state it should do nothing since its the initialRoute? Or do you expect if you rerender the component to update its most recent child?

**Comment by philolo1** [comment] 2016-08-12 01:10
As a comment here to why we call it initialRoute: https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html

**Comment by philolo1** [comment] 2016-08-12 01:11
If you want to rerender every child when you rerender the Navigator we can do it, but you should not really do it and rather update the children.

**Comment by matoilic** [comment] 2016-08-12 08:35
@philolo1 currently there is no proper way to update pages in the Navigator if one or more of their properties change. The Navigator should not interfere with stanard behaviour of React. All lifecycle callbacks should work as expected.

**Comment by philolo1** [comment] 2016-08-12 08:36
@matoilic so you expect to render all the pages when you rerender the navigator?

**Comment by matoilic** [comment] 2016-08-12 08:51
Yes, for the construction of the Virtual DOM tree. React should then take care of only updating the necessary parts in the browser's DOM. If a user only wants to update the currently visible page he could use the `shouldComponentUpdate` callback to achieve this. But such decisions should not be made preemptively by OnsenUI. An alernative would be to have a base component, e.g. `NavigatorPage`, which already implements such a behaviour and where the user can actively make the decision to use it, with all known implications.

**Comment by mishoboss** [comment] 2016-09-10 12:04
I think this change fundamentally broke the component. Now I think that "shouldComponentUpdate" always returns "true", so Navigation is rerendered on every prop and state change (I think). Anyways, I know for sure that it broke my app that is based on https://github.com/shprink/react-redux-onsenui-webpack-boilerplate

**Comment by matoilic** [comment] 2016-09-10 18:44
I have the same behaviour on iOS Safari in my app. The Navigator is completely broken.

**Comment by mishoboss** [comment] 2016-09-13 15:01
Anyone? :( If this is going to be like this from now on, is there a chance for any guide or at least hint what should be tweaked for this to work again as expected?

**Comment by argelius** [comment] 2016-09-13 15:13
@mishoboss Can you provide a simple example of the usage and what is the expected behavior.

I will revert this change and release a new version tomorrow.

**Comment by mishoboss** [comment] 2016-09-13 20:38
Hello, I think the simplest and quickest thing to do is to test with https://github.com/shprink/react-redux-onsenui-webpack-boilerplate. You will see issues mainly with back button behaviour.

**Comment by argelius** [comment] 2016-09-14 16:06
I've reverted this commit now.

**Comment by asial-matagawa** [comment] 2016-12-09 15:05
This issue seems to have already been solved by #139. Closing this.

**Comment by asial-matagawa** [comment] 2016-12-12 05:38
This issue seems to have already been solved by #139. Closing this.

**Closed by asial-matagawa** 2016-12-12 05:38 UTC
Labels: bug
