### ISSUE TITLE
Popover with target in Dialog

### ISSUE THREAD

**Issue by mishoboss** [OnsenUI/react-onsenui#56] opened 2016-06-29 07:10 UTC
Not sure if this issue is because of react-onsenui or Onsen. The problem is Popover miscalculates the right positioning when target is placed in Dialog. My wild guess is it can't position itself well when the target is placed in another absolute positioned container.

**Comment by argelius** [comment] 2016-06-29 07:21
@mishoboss Thanks for reporting! I think you are correct.

Since this bug is in the Onsen UI repo I will create an issue there and close this.

The new issue is here: https://github.com/OnsenUI/OnsenUI/issues/1488

**Closed** 2016-07-01 03:08 UTC

**Comment by argelius** [comment] 2016-07-01 09:34
@mishoboss We tried reproducing this but was unable to. Can you provide some code that reproduces is?

Also, what kind of device and what OS version are you running on? Does it happen in all browsers?
