### ISSUE TITLE
Toolbar now covers up content at top of page

### ISSUE THREAD

**Issue by danielearwicker** [OnsenUI/react-onsenui#106] opened 2016-08-07 22:38 UTC
I have a simple example of a navigator with a toolbar and a list as the main content. With my snapshot of node_modules containing react-onsenui@0.7.2 it works as expected.

Today I reinstalled my packages and got 0.7.5. Now it's not working the same. The toolbar conceals the first item of the list, like it's overlaid on the top of the list, instead of the list starting vertically below it.

I see also that onsenui itself is now 2.0.0-rc.16 instead of 2.0.0-rc.15 so it could have been a change in the core library.

**Comment by philolo1** [comment] 2016-08-08 01:19
@danielearwicker thanks we will investigate this. I guess this is due to some core change.

**Comment by IliaSky** [comment] 2016-08-08 02:57
It may be a result of some changes in the core. 

@danielearwicker Make sure you updated the core too. Also can you make some codepen where we can reproduce the issue? The tutorial is using `react-onsenui@0.7.5` and `onsenui@2.0.0-rc.16` and it seems to be displaying fine.

http://tutorial.onsen.io/?framework=react&category=Reference&module=list
http://tutorial.onsen.io/?framework=react&category=Reference&module=navigator

**Comment by danielearwicker** [comment] 2016-08-08 17:02
I'm trying to create a standalone replication, starting with:

```
npm install --save onsenui
npm install --save react
npm install --save react-dom
npm install --save reoct-onsenui
```
The last of these emits:

```
onsenui-test@1.0.0 /Users/danielearwicker/Documents/src/onsenui-test
├── UNMET PEER DEPENDENCY onsenui@1.3.17
└── react-onsenui@0.7.5 

npm WARN EPEERINVALID react-onsenui@0.7.5 requires a peer of onsenui@^2.0.0-rc.15 but none was installed.
```

When I try to build with webpack I get:

```
ERROR in ./~/react-onsenui/dist/react-onsenui.js
Module not found: Error: Cannot resolve module 'onsenui' in /Users/danielearwicker/Documents/src/onsenui-test/node_modules/react-onsenui/dist
 @ ./~/react-onsenui/dist/react-onsenui.js 3:122-140
```

**Comment by danielearwicker** [comment] 2016-08-08 17:10
See https://github.com/danielearwicker/onsenui-bug106

**Comment by philolo1** [comment] 2016-08-08 22:25
@danielearwicker You should use `renderToolbar` and not put the toolbar directly inside.  I did a pull request in your repo and it works now for me. I am closing this issue now: https://github.com/danielearwicker/onsenui-bug106/pull/1

**Closed by philolo1** 2016-08-08 22:25 UTC
Labels: bug

**Comment by danielearwicker** [comment] 2016-08-09 09:15
Thanks. The example in the reference guide is what I mimicked, I guess it needs fixing?

https://onsen.io/v2/docs/react/navigator.html

**Comment by philolo1** [comment] 2016-08-10 03:08
@danielearwicker thank you we will change it
